import Head from 'next/head';
import Link from 'next/link';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const SECTIONS = [
  {
    title: 'Getting Started',
    icon: '🚀',
    items: [
      { title: 'What is snspokes?', desc: 'The definitive reference for ServiceNow Integration Hub spokes with AI-powered explanations.' },
      { title: 'How to Search', desc: 'Type any spoke name in the search box on the homepage or search page to get instant results.' },
      { title: 'Understanding Spoke Pages', desc: 'Each spoke page shows official description, developer tips, AI explanation, setup guide, actions, and code examples.' },
    ]
  },
  {
    title: 'Integration Hub Basics',
    icon: '🔌',
    items: [
      { title: 'What is Integration Hub?', desc: 'ServiceNow Integration Hub is a platform for connecting ServiceNow to third-party systems using pre-built spokes.' },
      { title: 'What is a Spoke?', desc: 'A spoke is a pre-built integration package containing triggers, actions, and connections for a specific application like Slack or Jira.' },
      { title: 'Credential Types', desc: 'Spokes use different authentication methods: OAuth 2.0, API Key, Basic Auth, or custom credentials depending on the target system.' },
    ]
  },
  {
    title: 'Using the AI Assistant',
    icon: '🤖',
    items: [
      { title: 'Chatbot', desc: 'Click the chat bubble in the bottom right to ask any question about ServiceNow Integration Hub spokes.' },
      { title: 'AI Explanations', desc: 'Every spoke page includes an AI-generated explanation in simple English, making it easy to understand even complex integrations.' },
      { title: 'Limitations', desc: 'AI responses are generated by a local Ollama model. For the most accurate information, always verify with official ServiceNow documentation.' },
    ]
  },
  {
    title: 'Popular Spokes',
    icon: '⭐',
    items: [
      { title: 'Slack', desc: 'Send messages, create channels, manage users. Plugin: com.glide.hub.spoke.slack. Auth: OAuth 2.0.', link: '/spoke/slack' },
      { title: 'Jira', desc: 'Create issues, update sprints, manage projects. Plugin: com.glide.hub.spoke.jira. Auth: OAuth 2.0.', link: '/spoke/jira' },
      { title: 'GitHub', desc: 'Manage repos, issues, pull requests. Plugin: com.glide.hub.spoke.github. Auth: OAuth 2.0.', link: '/spoke/github' },
      { title: 'AWS', desc: 'Manage EC2, S3, Lambda. Plugin: com.glide.hub.spoke.aws. Auth: AWS Credentials.', link: '/spoke/aws' },
    ]
  },
];

export default function Docs() {
  return (
    <>
      <Head>
        <title>Documentation — snspokes</title>
        <meta name="description" content="Learn how to use snspokes and ServiceNow Integration Hub spokes." />
      </Head>
      <Navbar />
      <main style={{ paddingTop: '80px', minHeight: '100vh' }}>
        <section style={{ padding: '60px 24px', borderBottom: '1px solid #1e1e2e', background: 'linear-gradient(180deg, rgba(108,99,255,0.04) 0%, transparent 100%)' }}>
          <div style={{ maxWidth: '900px', margin: '0 auto' }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '4px 12px', borderRadius: '20px', border: '1px solid rgba(108,99,255,0.3)', background: 'rgba(108,99,255,0.08)', marginBottom: '20px' }}>
              <span style={{ fontSize: '12px', color: '#8b85ff' }}>Documentation</span>
            </div>
            <h1 style={{ fontSize: '40px', fontWeight: '800', color: '#fff', marginBottom: '16px' }}>Documentation</h1>
            <p style={{ color: '#6b6b8a', fontSize: '16px', lineHeight: '1.7' }}>Everything you need to know about using snspokes and ServiceNow Integration Hub spokes.</p>
          </div>
        </section>

        <section style={{ padding: '60px 24px' }}>
          <div style={{ maxWidth: '900px', margin: '0 auto' }}>
            {SECTIONS.map(section => (
              <div key={section.title} style={{ marginBottom: '56px' }}>
                <h2 style={{ display: 'flex', alignItems: 'center', gap: '12px', fontSize: '24px', fontWeight: '800', color: '#fff', marginBottom: '24px' }}>
                  <span>{section.icon}</span> {section.title}
                </h2>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                  {section.items.map(item => (
                    <div key={item.title} style={{ padding: '24px', background: '#0f0f1a', borderRadius: '16px', border: '1px solid #1e1e2e' }}>
                      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '16px' }}>
                        <div style={{ flex: 1 }}>
                          <h3 style={{ color: '#fff', fontSize: '16px', fontWeight: '700', marginBottom: '8px' }}>{item.title}</h3>
                          <p style={{ color: '#9999bb', fontSize: '14px', lineHeight: '1.6' }}>{item.desc}</p>
                        </div>
                        {item.link && (
                          <Link href={item.link} style={{ flexShrink: 0, padding: '8px 16px', background: 'rgba(108,99,255,0.1)', border: '1px solid rgba(108,99,255,0.2)', borderRadius: '8px', color: '#8b85ff', textDecoration: 'none', fontSize: '13px', whiteSpace: 'nowrap', transition: 'all 0.2s' }}
                            onMouseEnter={e => { e.currentTarget.style.background = 'rgba(108,99,255,0.2)'; e.currentTarget.style.borderColor = '#6c63ff'; }}
                            onMouseLeave={e => { e.currentTarget.style.background = 'rgba(108,99,255,0.1)'; e.currentTarget.style.borderColor = 'rgba(108,99,255,0.2)'; }}
                          >View spoke →</Link>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}

            {/* External Links */}
            <div style={{ padding: '32px', background: 'rgba(108,99,255,0.05)', borderRadius: '16px', border: '1px solid rgba(108,99,255,0.2)' }}>
              <h3 style={{ color: '#fff', fontSize: '18px', fontWeight: '700', marginBottom: '16px' }}>External Resources</h3>
              <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
                {[
                  { label: 'ServiceNow Docs', href: 'https://docs.servicenow.com' },
                  { label: 'Integration Hub', href: 'https://docs.servicenow.com/bundle/washingtondc-integrate-applications/page/administer/integrationhub/concept/integrationhub.html' },
                  { label: 'Community Forums', href: 'https://community.servicenow.com' },
                  { label: 'ServiceNow Store', href: 'https://store.servicenow.com' },
                ].map(link => (
                  <a key={link.label} href={link.href} target="_blank" rel="noopener noreferrer"
                    style={{ padding: '10px 20px', background: '#0f0f1a', border: '1px solid #1e1e2e', borderRadius: '10px', color: '#9999bb', textDecoration: 'none', fontSize: '14px', transition: 'all 0.2s' }}
                    onMouseEnter={e => { e.currentTarget.style.borderColor = '#6c63ff'; e.currentTarget.style.color = '#fff'; }}
                    onMouseLeave={e => { e.currentTarget.style.borderColor = '#1e1e2e'; e.currentTarget.style.color = '#9999bb'; }}
                  >{link.label} ↗</a>
                ))}
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
