// Complete ServiceNow Integration Hub spoke dataset
// Source: ServiceNow Store, docs.servicenow.com, community release notes
// Last verified: 2025 (Washington DC / Xanadu releases)

const SPOKES = [
  // ── COMMUNICATION ──────────────────────────────────────────
  { slug:'slack', name:'Slack', icon:'💬', category:'Communication', tier:'professional',
    plugin_id:'com.snc.slack_spoke', credential_type:'OAuth 2.0',
    description:'Send messages, manage channels, look up users, and post notifications to Slack workspaces directly from ServiceNow flows.',
    actions:['Send Message','Create Channel','Look Up User','Add User to Channel','Post Notification','Create Direct Message','Look Up Channel','Archive Channel','Update Message'],
    setup_steps:['Install Slack spoke from ServiceNow Store','Create Slack App at api.slack.com','Configure OAuth 2.0 scopes: channels:write, chat:write, users:read','Add Bot Token to Connection Alias in ServiceNow','Test connection with Send Message action'],
    common_errors:['channel_not_found — ensure channel ID not name','not_authed — OAuth token expired, re-authenticate','missing_scope — add required scope in Slack App settings'],
    min_version:'Orlando', tags:['messaging','notifications','chatops'] },

  { slug:'microsoft-teams', name:'Microsoft Teams', icon:'🟦', category:'Communication', tier:'professional',
    plugin_id:'com.snc.microsoft_teams_spoke', credential_type:'OAuth 2.0',
    description:'Post messages, create meetings, manage teams and channels in Microsoft Teams from ServiceNow workflows.',
    actions:['Send Message','Create Team','Add Member','Create Channel','Create Meeting','Look Up User','Post Adaptive Card','Send Direct Message'],
    setup_steps:['Register App in Azure Active Directory','Grant API permissions: ChannelMessage.Send, Chat.Create, OnlineMeetings.ReadWrite','Configure OAuth 2.0 in ServiceNow Connection Alias','Test with Send Message action'],
    common_errors:['403 Forbidden — missing API permissions in Azure','Token expired — re-authenticate connection alias','Channel not found — use channel ID not display name'],
    min_version:'Paris', tags:['messaging','microsoft','collaboration'] },

  { slug:'zoom', name:'Zoom', icon:'📹', category:'Communication', tier:'starter',
    plugin_id:'com.snc.zoom_spoke', credential_type:'OAuth 2.0',
    description:'Create and manage Zoom meetings, look up users, and send notifications from ServiceNow.',
    actions:['Create Meeting','Look Up User','Delete Meeting','Update Meeting','Get Meeting Details'],
    setup_steps:['Create Zoom OAuth App at marketplace.zoom.us','Configure scopes: meeting:write, user:read','Add credentials to ServiceNow Connection Alias'],
    common_errors:['invalid_token — OAuth flow needs to be re-completed','User not found — use Zoom user email not name'],
    min_version:'Quebec', tags:['video','meetings'] },

  { slug:'webex', name:'Cisco Webex', icon:'🔵', category:'Communication', tier:'starter',
    plugin_id:'com.snc.webex_spoke', credential_type:'OAuth 2.0',
    description:'Send messages and create meetings in Cisco Webex from ServiceNow automation flows.',
    actions:['Send Message','Create Meeting','Look Up Room','Add Member to Room'],
    setup_steps:['Create Webex Bot at developer.webex.com','Copy Bot Access Token','Create Connection Alias with Bearer Token auth'],
    common_errors:['Room not found — use room ID from Look Up Room action','Token revoked — regenerate bot token'],
    min_version:'Quebec', tags:['cisco','meetings','messaging'] },

  // ── PROJECT MANAGEMENT ──────────────────────────────────────
  { slug:'jira', name:'Jira', icon:'🔷', category:'Project Management', tier:'professional',
    plugin_id:'com.snc.jira_spoke', credential_type:'Basic Auth / OAuth 2.0',
    description:'Create, update, and sync Jira issues with ServiceNow incidents and changes. Bi-directional integration for ITSM and agile development.',
    actions:['Create Issue','Update Issue','Look Up Issue','Add Comment','Transition Issue','Look Up Project','Assign Issue','Create Epic','Look Up Sprint','Add Attachment'],
    setup_steps:['Install Jira spoke from ServiceNow Store','Generate Jira API Token at id.atlassian.com','Create Connection Alias with Basic Auth (email + API token)','Map ServiceNow fields to Jira fields in flow','Set up bi-directional webhook for real-time sync'],
    common_errors:['401 Unauthorized — API token vs password confusion (use API token)','Project not found — use project key not name','Transition not available — issue must be in correct state'],
    min_version:'New York', tags:['agile','devops','ticketing'] },

  { slug:'github', name:'GitHub', icon:'🐙', category:'DevOps', tier:'professional',
    plugin_id:'com.snc.github_spoke', credential_type:'OAuth 2.0 / Personal Access Token',
    description:'Create issues, manage pull requests, trigger workflows, and sync code changes with ServiceNow change management.',
    actions:['Create Issue','Look Up Issue','Create Pull Request','Merge Pull Request','Trigger Workflow','Look Up Repository','Add Label','Create Comment','Look Up User','Close Issue'],
    setup_steps:['Create GitHub OAuth App or Personal Access Token','Grant scopes: repo, issues, workflow','Create Connection Alias in ServiceNow','Test with Look Up Repository action'],
    common_errors:['404 Not Found — repository may be private, check token scopes','Validation Failed — required fields missing (title for issues)','Workflow not found — workflow file must exist in .github/workflows'],
    min_version:'Orlando', tags:['git','devops','cicd'] },

  { slug:'gitlab', name:'GitLab', icon:'🦊', category:'DevOps', tier:'professional',
    plugin_id:'com.snc.gitlab_spoke', credential_type:'Personal Access Token',
    description:'Manage GitLab issues, merge requests, and CI/CD pipelines from ServiceNow change workflows.',
    actions:['Create Issue','Look Up Issue','Create Merge Request','Trigger Pipeline','Look Up Project','Add Comment'],
    setup_steps:['Generate GitLab Personal Access Token (scope: api)','Create Connection Alias with Bearer Token','Test with Look Up Project action'],
    common_errors:['401 Unauthorized — token needs api scope','Project not found — use numeric project ID'],
    min_version:'Quebec', tags:['git','devops','cicd'] },

  { slug:'azure-devops', name:'Azure DevOps', icon:'🔵', category:'DevOps', tier:'professional',
    plugin_id:'com.snc.azure_devops_spoke', credential_type:'Personal Access Token',
    description:'Create work items, manage pipelines, and sync Azure DevOps boards with ServiceNow.',
    actions:['Create Work Item','Update Work Item','Look Up Work Item','Trigger Pipeline','Look Up Build','Create Pull Request'],
    setup_steps:['Generate Azure DevOps PAT at dev.azure.com','Grant scopes: Work Items (read/write), Build (execute)','Create Connection Alias in ServiceNow'],
    common_errors:['TF401019 — team project not found','Work item type invalid — check allowed types for project'],
    min_version:'Paris', tags:['azure','microsoft','devops'] },

  // ── CLOUD ───────────────────────────────────────────────────
  { slug:'aws', name:'AWS', icon:'☁️', category:'Cloud', tier:'enterprise',
    plugin_id:'com.snc.aws_spoke', credential_type:'AWS Access Key / IAM Role',
    description:'Manage EC2 instances, S3 buckets, Lambda functions, and other AWS services from ServiceNow. Supports multiple regions via single connection.',
    actions:['Start EC2 Instance','Stop EC2 Instance','Look Up EC2 Instance','Create S3 Bucket','Upload to S3','Invoke Lambda','Send SNS Notification','Create SQS Message','Look Up IAM User','Describe RDS Instance'],
    setup_steps:['Create IAM User with programmatic access','Attach required policies (EC2FullAccess, S3FullAccess, etc.)','Create Connection Alias with Access Key ID and Secret','Configure region in connection attributes','Test with Look Up EC2 Instance'],
    common_errors:['AuthFailure — invalid Access Key or Secret','UnauthorizedOperation — IAM policy missing required permission','InvalidRegion — check region format (us-east-1 not US East)'],
    min_version:'New York', tags:['amazon','cloud','infrastructure'] },

  { slug:'azure', name:'Microsoft Azure', icon:'🔷', category:'Cloud', tier:'enterprise',
    plugin_id:'com.snc.azure_spoke', credential_type:'OAuth 2.0 (Service Principal)',
    description:'Manage Azure VMs, resource groups, and subscriptions from ServiceNow workflows.',
    actions:['Start VM','Stop VM','Look Up VM','Create Resource Group','Look Up Subscription','Manage Storage Account'],
    setup_steps:['Create Service Principal in Azure AD','Grant Contributor role on subscription','Configure OAuth with tenant ID, client ID, client secret','Create Connection Alias in ServiceNow'],
    common_errors:['AuthorizationFailed — service principal missing role assignment','Resource not found — check subscription and resource group names'],
    min_version:'Paris', tags:['microsoft','cloud','infrastructure'] },

  { slug:'azure-active-directory', name:'Azure Active Directory', icon:'👤', category:'Identity', tier:'professional',
    plugin_id:'com.snc.azure_ad_spoke', credential_type:'OAuth 2.0',
    description:'Create, update, and manage users and groups in Azure AD (Entra ID). Automate user provisioning and deprovisioning from ServiceNow HR and ITSM workflows.',
    actions:['Create User','Update User','Disable User','Enable User','Look Up User','Add User to Group','Remove from Group','Create Group','Look Up Group','Reset Password','Revoke Sign-In Sessions'],
    setup_steps:['Register app in Azure AD with API permissions','Grant: User.ReadWrite.All, Group.ReadWrite.All','Configure OAuth 2.0 in Connection Alias','Test with Look Up User action'],
    common_errors:['Request_ResourceNotFound — user UPN vs object ID confusion','Authorization_RequestDenied — missing admin consent for permissions','Directory_QuotaExceeded — Azure AD object limit reached'],
    min_version:'Quebec', tags:['microsoft','identity','provisioning','azure'] },

  { slug:'google-workspace', name:'Google Workspace', icon:'🔴', category:'Productivity', tier:'professional',
    plugin_id:'com.snc.google_workspace_spoke', credential_type:'OAuth 2.0',
    description:'Manage Google Workspace users, groups, Drive files, and Calendar events from ServiceNow.',
    actions:['Create User','Update User','Suspend User','Look Up User','Add to Group','Create Drive File','Share Drive File','Create Calendar Event'],
    setup_steps:['Create OAuth credentials in Google Cloud Console','Enable Admin SDK, Drive API, Calendar API','Configure domain-wide delegation','Create Connection Alias in ServiceNow'],
    common_errors:['403 insufficientPermissions — OAuth scope missing','Domain not found — verify domain ownership in Google Console'],
    min_version:'Quebec', tags:['google','identity','cloud'] },

  // ── ITSM / SERVICE MANAGEMENT ───────────────────────────────
  { slug:'pagerduty', name:'PagerDuty', icon:'🚨', category:'Monitoring', tier:'professional',
    plugin_id:'com.snc.pagerduty_spoke', credential_type:'API Key',
    description:'Create, acknowledge, and resolve PagerDuty incidents from ServiceNow. Sync on-call schedules and escalation policies.',
    actions:['Create Incident','Acknowledge Incident','Resolve Incident','Look Up Incident','Get On-Call User','Trigger Alert','Look Up Service','Create Note'],
    setup_steps:['Generate PagerDuty API key in Account Settings','Create Connection Alias with API Key auth','Map ServiceNow urgency to PagerDuty severity','Configure webhook for bi-directional sync'],
    common_errors:['Invalid routing_key — use Integration Key not API Key for Events API','Not Found — incident ID must be PagerDuty incident ID'],
    min_version:'New York', tags:['monitoring','alerting','oncall'] },

  { slug:'opsgenie', name:'OpsGenie', icon:'🔔', category:'Monitoring', tier:'professional',
    plugin_id:'com.snc.opsgenie_spoke', credential_type:'API Key',
    description:'Create and manage OpsGenie alerts and on-call schedules from ServiceNow incident workflows.',
    actions:['Create Alert','Close Alert','Acknowledge Alert','Look Up Alert','Get On-Call','Add Note'],
    setup_steps:['Generate OpsGenie API key','Create Connection Alias in ServiceNow','Configure alert priority mapping'],
    common_errors:['Could not authenticate — API key needs Full Access not Read access'],
    min_version:'Paris', tags:['monitoring','alerting'] },

  { slug:'zendesk', name:'Zendesk', icon:'🎫', category:'Customer Service', tier:'professional',
    plugin_id:'com.snc.zendesk_spoke', credential_type:'OAuth 2.0 / API Token',
    description:'Create, update, and sync Zendesk tickets with ServiceNow cases and incidents.',
    actions:['Create Ticket','Update Ticket','Look Up Ticket','Add Comment','Look Up User','Create User','Close Ticket','Look Up Organization'],
    setup_steps:['Enable API access in Zendesk Admin','Generate API token or configure OAuth','Create Connection Alias in ServiceNow','Map ticket fields between platforms'],
    common_errors:['401 Unauthorized — use email/token format not just token','Record Not Found — ticket ID is numeric'],
    min_version:'Quebec', tags:['crm','support','customer'] },

  { slug:'servicenow-itsm', name:'ServiceNow ITSM', icon:'🔧', category:'ITSM', tier:'starter',
    plugin_id:'com.snc.itsm_spoke', credential_type:'Basic Auth / OAuth 2.0',
    description:'Connect multiple ServiceNow instances — create incidents, changes, and problems across instances using the Remote Instance spoke.',
    actions:['Create Incident','Update Incident','Create Change Request','Create Problem','Look Up Record','Create Task','Update Task'],
    setup_steps:['Configure MID Server if connecting on-prem instances','Create service account on target instance','Set up OAuth or Basic Auth Connection Alias','Test REST call to target instance'],
    common_errors:['SSL Certificate error — configure trusted cert on MID Server','ACL restriction — service account needs appropriate roles'],
    min_version:'New York', tags:['itsm','multi-instance'] },

  // ── IDENTITY / SECURITY ─────────────────────────────────────
  { slug:'okta', name:'Okta', icon:'🔐', category:'Identity', tier:'professional',
    plugin_id:'com.snc.okta_spoke', credential_type:'API Token',
    description:'Provision, deprovision, and manage Okta users and groups from ServiceNow HR and ITSM workflows. Automate joiner-mover-leaver processes.',
    actions:['Create User','Deactivate User','Activate User','Look Up User','Add to Group','Remove from Group','Look Up Group','Reset Password','Suspend User','List User Groups'],
    setup_steps:['Generate Okta API token with Super Admin','Create Connection Alias in ServiceNow with Bearer Token auth','Configure Okta domain URL in connection properties','Test with Look Up User action'],
    common_errors:['E0000011 — invalid token, check token not expired','E0000095 — user already in group','E0000007 — resource not found, verify user email format'],
    min_version:'Quebec', tags:['identity','sso','provisioning'] },

  { slug:'sailpoint', name:'SailPoint', icon:'⚓', category:'Identity', tier:'enterprise',
    plugin_id:'com.snc.sailpoint_spoke', credential_type:'OAuth 2.0',
    description:'Request and manage access certifications, entitlements, and identity governance workflows through SailPoint IdentityNow.',
    actions:['Create Access Request','Look Up Identity','Look Up Entitlement','Get Certification','Revoke Access'],
    setup_steps:['Configure OAuth client in SailPoint tenant','Get tenant URL, client ID, client secret','Create Connection Alias in ServiceNow'],
    common_errors:['400 Bad Request — identity ID format is UUID not name'],
    min_version:'San Diego', tags:['identity','governance','access'] },

  { slug:'cyberark', name:'CyberArk', icon:'🛡️', category:'Security', tier:'enterprise',
    plugin_id:'com.snc.cyberark_spoke', credential_type:'CyberArk Central Credential Provider',
    description:'Retrieve and rotate privileged credentials stored in CyberArk Vault from ServiceNow workflows.',
    actions:['Get Credential','Look Up Account','Change Password','Verify Credential'],
    setup_steps:['Configure CyberArk Central Credential Provider (CCP)','Set up application authentication in CyberArk','Create Connection Alias in ServiceNow'],
    common_errors:['ITATS007E — application not authorized','APPAP227E — safe not found'],
    min_version:'San Diego', tags:['security','pam','credentials'] },

  // ── CRM / SALES ─────────────────────────────────────────────
  { slug:'salesforce', name:'Salesforce', icon:'☁️', category:'CRM', tier:'enterprise',
    plugin_id:'com.snc.salesforce_spoke', credential_type:'OAuth 2.0',
    description:'Sync Salesforce accounts, contacts, cases, and opportunities with ServiceNow. Enable bi-directional CRM and ITSM integration.',
    actions:['Create Record','Update Record','Look Up Record','Create Case','Update Case','Look Up Account','Create Contact','Look Up Opportunity','Execute SOQL Query','Create Attachment'],
    setup_steps:['Create Connected App in Salesforce Setup','Enable OAuth settings: api, refresh_token scopes','Create Connection Alias with OAuth 2.0 in ServiceNow','Map Salesforce objects to ServiceNow tables'],
    common_errors:['INVALID_SESSION_ID — OAuth token expired, re-authenticate','INVALID_FIELD — field API name is case-sensitive','REQUIRED_FIELD_MISSING — check required fields for sObject type'],
    min_version:'Paris', tags:['crm','sales','cloud'] },

  { slug:'hubspot', name:'HubSpot', icon:'🧲', category:'CRM', tier:'professional',
    plugin_id:'com.snc.hubspot_spoke', credential_type:'OAuth 2.0 / API Key',
    description:'Create and manage HubSpot contacts, deals, and tickets from ServiceNow workflows.',
    actions:['Create Contact','Update Contact','Look Up Contact','Create Deal','Create Ticket','Add Note'],
    setup_steps:['Create HubSpot Private App with required scopes','Or configure OAuth 2.0 for public apps','Create Connection Alias in ServiceNow'],
    common_errors:['Property not found — use internal property name not label'],
    min_version:'Quebec', tags:['crm','marketing','sales'] },

  // ── HR / ERP ─────────────────────────────────────────────────
  { slug:'workday', name:'Workday', icon:'💼', category:'HR', tier:'enterprise',
    plugin_id:'com.snc.workday_spoke', credential_type:'Basic Auth (ISU)',
    description:'Sync employee data, manage HR transactions, and trigger Workday business processes from ServiceNow HR Service Delivery workflows.',
    actions:['Get Worker','Look Up Employee','Hire Employee','Terminate Employee','Change Job','Create Position','Look Up Organizational Unit','Update Employee'],
    setup_steps:['Create Integration System User (ISU) in Workday','Assign appropriate security groups to ISU','Configure Basic Auth Connection Alias','Set Workday tenant URL in connection properties','Test with Get Worker action'],
    common_errors:['Invalid credentials — ISU password policy may have forced change','Validation error — required fields vary by Workday tenant config','Access denied — ISU missing required domain security policy'],
    min_version:'Paris', tags:['hr','hcm','payroll'] },

  { slug:'successfactors', name:'SAP SuccessFactors', icon:'🏢', category:'HR', tier:'enterprise',
    plugin_id:'com.snc.successfactors_spoke', credential_type:'OAuth 2.0 SAML Bearer',
    description:'Sync employee lifecycle events between SAP SuccessFactors and ServiceNow HR Service Delivery.',
    actions:['Look Up Employee','Get Position','Look Up Job Requisition','Update Employee Profile'],
    setup_steps:['Configure OAuth in SuccessFactors Admin Center','Set up SAML assertion','Create Connection Alias in ServiceNow with company ID'],
    common_errors:['401 — company ID case-sensitive','Employee not found — use Employee Central user ID'],
    min_version:'Quebec', tags:['hr','sap','hcm'] },

  { slug:'sap', name:'SAP ERP', icon:'🏗️', category:'ERP', tier:'enterprise',
    plugin_id:'com.snc.sap_spoke', credential_type:'Basic Auth / OAuth 2.0',
    description:'Integrate with SAP ERP systems using RFC calls and OData APIs. Manage purchase orders, work orders, and financial data.',
    actions:['Execute RFC Function','Look Up Material','Create Purchase Order','Get Work Order','Look Up Vendor','Create Service Entry Sheet'],
    setup_steps:['Configure SAP system connection (host, system number, client)','Create service user in SAP with RFC authorization','Install SAP JCo connector on MID Server','Create Connection Alias with SAP credentials'],
    common_errors:['JCo library not found — install SAP JCo on MID Server','ABAP runtime error — check RFC function authorization'],
    min_version:'New York', tags:['sap','erp','finance'] },

  // ── ITSM TOOLS ───────────────────────────────────────────────
  { slug:'servicenow-cmdb', name:'ServiceNow CMDB', icon:'🗄️', category:'ITSM', tier:'starter',
    plugin_id:'com.snc.cmdb_spoke', credential_type:'Internal',
    description:'Query and update the ServiceNow CMDB — look up CIs, create relationships, and manage configuration items from flows.',
    actions:['Look Up CI','Create CI','Update CI','Create Relationship','Look Up Relationship','Get CI Dependencies'],
    setup_steps:['No external connection needed — uses internal ServiceNow APIs','Configure appropriate ACLs for service account'],
    common_errors:['CI not found — use sys_id not display name','Class not found — ensure CI class exists in CMDB'],
    min_version:'New York', tags:['cmdb','itsm','configuration'] },

  { slug:'dynatrace', name:'Dynatrace', icon:'📊', category:'Monitoring', tier:'professional',
    plugin_id:'com.snc.dynatrace_spoke', credential_type:'API Token',
    description:'Create and close Dynatrace problems, look up entities, and trigger synthetic monitors from ServiceNow.',
    actions:['Create Problem','Close Problem','Look Up Problem','Get Entity','Trigger Synthetic Monitor','Push Event'],
    setup_steps:['Generate Dynatrace API token with required scopes','Create Connection Alias with Bearer token auth','Configure Dynatrace environment URL'],
    common_errors:['401 — token missing required API v2 scopes','Entity not found — use Dynatrace entity ID format'],
    min_version:'Quebec', tags:['monitoring','apm','observability'] },

  { slug:'datadog', name:'Datadog', icon:'🐕', category:'Monitoring', tier:'professional',
    plugin_id:'com.snc.datadog_spoke', credential_type:'API Key + Application Key',
    description:'Create Datadog events, manage monitors, and look up metrics from ServiceNow incident workflows.',
    actions:['Create Event','Trigger Monitor','Look Up Monitor','Mute Monitor','Get Metrics','Create Incident','Look Up Dashboard'],
    setup_steps:['Generate API Key and Application Key in Datadog','Create Connection Alias with both keys','Configure Datadog site (datadoghq.com or datadoghq.eu)'],
    common_errors:['403 Forbidden — Application Key needs correct permissions','Invalid API key — verify DD_SITE matches your Datadog region'],
    min_version:'Quebec', tags:['monitoring','metrics','observability'] },

  { slug:'splunk', name:'Splunk', icon:'🔍', category:'Security', tier:'enterprise',
    plugin_id:'com.snc.splunk_spoke', credential_type:'Bearer Token',
    description:'Run Splunk searches, look up notable events, and create incidents from Splunk alerts in ServiceNow.',
    actions:['Run Search','Look Up Notable Event','Create Notable Event','Acknowledge Alert','Look Up Index'],
    setup_steps:['Create Splunk service account','Generate auth token in Splunk Web','Create Connection Alias with Bearer Token','Configure Splunk host and port'],
    common_errors:['SSL verification failed — configure trusted cert','Permission denied — user needs can_delete capability for notable events'],
    min_version:'Quebec', tags:['siem','security','search'] },

  // ── PRODUCTIVITY ─────────────────────────────────────────────
  { slug:'docusign', name:'DocuSign', icon:'✍️', category:'Productivity', tier:'professional',
    plugin_id:'com.snc.docusign_spoke', credential_type:'OAuth 2.0',
    description:'Send documents for signature, check signing status, and retrieve completed envelopes from ServiceNow workflows.',
    actions:['Create Envelope','Send Envelope','Look Up Envelope Status','Download Signed Document','Void Envelope','Create Template'],
    setup_steps:['Create DocuSign developer account','Register OAuth application','Configure JWT authentication or Authorization Code flow','Create Connection Alias in ServiceNow'],
    common_errors:['AUTHORIZATION_INVALID_TOKEN — JWT key not configured correctly','ENVELOPE_DOES_NOT_EXIST — envelope ID required'],
    min_version:'Quebec', tags:['esignature','documents','contracts'] },

  { slug:'sharepoint', name:'SharePoint', icon:'📋', category:'Productivity', tier:'professional',
    plugin_id:'com.snc.sharepoint_spoke', credential_type:'OAuth 2.0',
    description:'Create, read, and manage SharePoint documents and list items from ServiceNow workflows.',
    actions:['Create List Item','Update List Item','Look Up List Item','Upload Document','Create Folder','Get Document','Share Document'],
    setup_steps:['Register app in Azure AD with SharePoint permissions','Configure OAuth 2.0 Connection Alias','Set SharePoint site URL in connection attributes'],
    common_errors:['Access denied — app needs Sites.ReadWrite.All permission','List not found — use list title exactly as shown'],
    min_version:'Paris', tags:['microsoft','documents','collaboration'] },

  { slug:'google-drive', name:'Google Drive', icon:'💛', category:'Productivity', tier:'professional',
    plugin_id:'com.snc.google_drive_spoke', credential_type:'OAuth 2.0',
    description:'Create, upload, and manage Google Drive files and folders from ServiceNow flows.',
    actions:['Create File','Upload File','Look Up File','Share File','Delete File','Copy File','Create Folder','Look Up File Revisions'],
    setup_steps:['Enable Drive API in Google Cloud Console','Configure OAuth 2.0 credentials','Create Connection Alias in ServiceNow'],
    common_errors:['403 insufficient permissions — add drive.file scope','File not found — use file ID not name'],
    min_version:'Quebec', tags:['google','storage','documents'] },

  // ── WORKFLOW / AUTOMATION ────────────────────────────────────
  { slug:'ansible', name:'Ansible', icon:'⚙️', category:'Automation', tier:'enterprise',
    plugin_id:'com.snc.ansible_spoke', credential_type:'Basic Auth',
    description:'Trigger Ansible Tower/AWX job templates from ServiceNow change workflows for infrastructure automation.',
    actions:['Launch Job Template','Look Up Job Template','Get Job Status','Look Up Inventory','Launch Workflow Template'],
    setup_steps:['Configure Ansible Tower/AWX API credentials','Create Connection Alias with Basic Auth','Map ServiceNow change fields to Ansible extra vars'],
    common_errors:['404 Not Found — job template ID must be numeric','Job failed immediately — check inventory and credentials in Ansible'],
    min_version:'New York', tags:['ansible','automation','infrastructure'] },

  { slug:'servicenow-orchestration', name:'ServiceNow Orchestration', icon:'🔄', category:'Automation', tier:'enterprise',
    plugin_id:'com.snc.orchestration', credential_type:'MID Server',
    description:'Run PowerShell scripts, SSH commands, and automated workflows via ServiceNow Orchestration and MID Server.',
    actions:['Run PowerShell Script','Run SSH Command','Transfer File','Start/Stop Windows Service','Run SQL Query'],
    setup_steps:['Install and configure MID Server','Validate MID Server connectivity','Set up activity packs (Windows, SSH, JDBC)'],
    common_errors:['MID Server offline — check MID Server service status','Access denied — MID Server service account needs local admin'],
    min_version:'New York', tags:['orchestration','midserver','automation'] },

  // ── AI / GENERATIVE AI ───────────────────────────────────────
  { slug:'openai', name:'OpenAI / ChatGPT', icon:'🤖', category:'AI', tier:'professional',
    plugin_id:'com.snc.generative_ai', credential_type:'API Key',
    description:'Integrate OpenAI GPT models into ServiceNow workflows for summarization, content generation, and AI-powered automation via the Generative AI Controller.',
    actions:['Generate Text','Summarize Content','QnA Prompt','Generic Prompt','Generate Embeddings'],
    setup_steps:['Generate OpenAI API Key at platform.openai.com','Install Generative AI Controller from ServiceNow Store','Create Connection Alias with OpenAI API key','Configure model (gpt-4, gpt-3.5-turbo) in flow'],
    common_errors:['429 Rate limit — upgrade OpenAI plan or add retry logic','Context length exceeded — truncate input text'],
    min_version:'Utah', tags:['ai','genai','llm','openai'] },

  { slug:'azure-openai', name:'Azure OpenAI', icon:'🧠', category:'AI', tier:'professional',
    plugin_id:'com.snc.azure_openai_spoke', credential_type:'API Key',
    description:'Use Azure-hosted OpenAI models for enterprise AI capabilities within ServiceNow workflows.',
    actions:['Generate Text','Summarize','Chat Completion','Generate Embeddings'],
    setup_steps:['Create Azure OpenAI resource','Deploy GPT model (gpt-4, gpt-35-turbo)','Get endpoint and API key','Create Connection Alias in ServiceNow'],
    common_errors:['DeploymentNotFound — model deployment name must match exactly','ContentFilter — input triggered Azure content filter'],
    min_version:'Utah', tags:['ai','azure','genai','microsoft'] },

  // ── ITSM / SERVICE DESK ──────────────────────────────────────
  { slug:'freshservice', name:'Freshservice', icon:'🌿', category:'ITSM', tier:'professional',
    plugin_id:'com.snc.freshservice_spoke', credential_type:'API Key',
    description:'Create and sync Freshservice tickets with ServiceNow incidents for multi-platform ITSM.',
    actions:['Create Ticket','Update Ticket','Look Up Ticket','Add Note','Close Ticket'],
    setup_steps:['Generate Freshservice API key in Profile Settings','Create Connection Alias with API key as password','Set Freshservice domain URL'],
    common_errors:['401 — use email:API_key format not just key','Validation failed — requester_id is required'],
    min_version:'Quebec', tags:['itsm','helpdesk'] },

  { slug:'snow-virtual-agent', name:'ServiceNow Virtual Agent', icon:'💬', category:'AI', tier:'starter',
    plugin_id:'com.glide.virtual_agent', credential_type:'Internal',
    description:'Build NLU-powered chatbot conversations that trigger ServiceNow flows and fetch information.',
    actions:['Send Message','Trigger Flow','Look Up Record','Present Options','Gather Input'],
    setup_steps:['Enable Virtual Agent in ServiceNow','Create topic in Virtual Agent Designer','Configure NLU model','Connect to MS Teams or Slack via channel integration'],
    common_errors:['Topic not triggering — check NLU training phrases','Flow not executing — verify flow trigger conditions'],
    min_version:'Orlando', tags:['chatbot','nlu','virtual-agent'] },

  // ── EMAIL / NOTIFICATIONS ────────────────────────────────────
  { slug:'sendgrid', name:'SendGrid', icon:'✉️', category:'Email', tier:'starter',
    plugin_id:'com.snc.sendgrid_spoke', credential_type:'API Key',
    description:'Send transactional emails via SendGrid from ServiceNow notification workflows.',
    actions:['Send Email','Send Template Email','Look Up Template','Create Contact'],
    setup_steps:['Generate SendGrid API key with Mail Send permission','Create Connection Alias with Bearer token','Configure sender identity'],
    common_errors:['403 Forbidden — sender identity not verified','Template not found — use template ID not name'],
    min_version:'Paris', tags:['email','notifications','sendgrid'] },

  { slug:'twilio', name:'Twilio', icon:'📱', category:'Communication', tier:'starter',
    plugin_id:'com.snc.twilio_spoke', credential_type:'Basic Auth (Account SID + Auth Token)',
    description:'Send SMS, make calls, and manage phone numbers via Twilio from ServiceNow.',
    actions:['Send SMS','Make Call','Look Up Message','Send WhatsApp Message'],
    setup_steps:['Get Twilio Account SID and Auth Token','Verify phone number in Twilio Console','Create Connection Alias with Account SID as user'],
    common_errors:['21211 — invalid To phone number (must include country code)','21606 — from number not capable of SMS'],
    min_version:'Paris', tags:['sms','communication','twilio'] },

  // ── ADDITIONAL ENTERPRISE SPOKES ─────────────────────────────
  { slug:'servicenow-hr', name:'ServiceNow HR Service Delivery', icon:'👤', category:'HR', tier:'starter',
    plugin_id:'com.snc.hr_spoke', credential_type:'Internal',
    description:'Create HR cases, look up employee profiles, and trigger HR workflows from ServiceNow flows.',
    actions:['Create HR Case','Update HR Case','Look Up Employee','Get Employee Profile','Create Life Event'],
    setup_steps:['HR Service Delivery plugin must be activated','Configure HR service catalog','Set appropriate HR role for service account'],
    common_errors:['HR case type not found — check case type configuration','Employee not found — use sys_id from sys_user table'],
    min_version:'New York', tags:['hr','hrsd','employee'] },

  { slug:'snow-security-ops', name:'ServiceNow SecOps', icon:'🛡️', category:'Security', tier:'enterprise',
    plugin_id:'com.snc.secops_spoke', credential_type:'Internal',
    description:'Create security incidents, look up vulnerabilities, and trigger threat intelligence lookups from ServiceNow Security Operations.',
    actions:['Create Security Incident','Look Up Vulnerability','Trigger Threat Lookup','Close Security Incident','Create Threat Intelligence'],
    setup_steps:['Security Operations plugin must be activated','Configure threat intelligence feeds','Set up SIEM integrations'],
    common_errors:['Plugin not activated — requires Security Operations subscription'],
    min_version:'New York', tags:['security','secops','siem'] },

  { slug:'servicenow-agile', name:'ServiceNow Agile Development', icon:'📌', category:'Project Management', tier:'starter',
    plugin_id:'com.snc.agile_spoke', credential_type:'Internal',
    description:'Create stories, sprints, and epics in ServiceNow Agile Development from Flow Designer.',
    actions:['Create Story','Update Story','Create Sprint','Create Epic','Move to Sprint'],
    setup_steps:['Agile Development 2.0 plugin must be activated'],
    common_errors:['Sprint not found — sprint must be in active state'],
    min_version:'Paris', tags:['agile','scrum','development'] },

  { slug:'servicenow-grc', name:'ServiceNow GRC', icon:'📊', category:'Compliance', tier:'enterprise',
    plugin_id:'com.snc.grc_spoke', credential_type:'Internal',
    description:'Create risks, controls, and audit tasks from ServiceNow GRC through automated workflows.',
    actions:['Create Risk','Update Control','Create Audit Task','Look Up Policy','Create Issue'],
    setup_steps:['GRC plugin must be activated','Configure risk scoring matrices'],
    common_errors:['Risk framework not found — configure risk statement framework first'],
    min_version:'Quebec', tags:['grc','compliance','risk'] },

  { slug:'snow-discovery', name:'ServiceNow Discovery', icon:'🔭', category:'ITSM', tier:'enterprise',
    plugin_id:'com.snc.discovery_spoke', credential_type:'MID Server',
    description:'Trigger Discovery scans and look up discovered CIs from ServiceNow workflows.',
    actions:['Trigger Discovery','Look Up Discovery Status','Get Discovered CIs'],
    setup_steps:['Discovery plugin must be activated','Configure MID Server with Discovery access'],
    common_errors:['No MID Server available — check MID Server status'],
    min_version:'New York', tags:['discovery','cmdb','infrastructure'] },

  { slug:'servicenow-csm', name:'ServiceNow CSM', icon:'🎧', category:'Customer Service', tier:'professional',
    plugin_id:'com.snc.csm_spoke', credential_type:'Internal',
    description:'Create and manage customer service cases, accounts, and contacts from ServiceNow Customer Service Management.',
    actions:['Create Case','Update Case','Look Up Account','Create Contact','Close Case'],
    setup_steps:['CSM plugin must be activated','Configure customer portal'],
    common_errors:['Account not found — CSM uses account table not company'],
    min_version:'New York', tags:['csm','customer-service','crm'] },

  { slug:'box', name:'Box', icon:'📦', category:'Productivity', tier:'professional',
    plugin_id:'com.snc.box_spoke', credential_type:'OAuth 2.0',
    description:'Manage Box files, folders, and collaborations from ServiceNow workflows.',
    actions:['Upload File','Create Folder','Share Folder','Look Up File','Delete File','Add Collaborator'],
    setup_steps:['Create Box OAuth 2.0 App','Configure redirect URIs','Create Connection Alias in ServiceNow'],
    common_errors:['Insufficient permissions — user needs collaboration access','File size limit — Box free tier has 250MB upload limit'],
    min_version:'Quebec', tags:['storage','documents','cloud'] },

  { slug:'servicenow-now-assist', name:'Now Assist (GenAI)', icon:'✨', category:'AI', tier:'professional',
    plugin_id:'com.glide.now_assist', credential_type:'Internal',
    description:'Use ServiceNow Now Assist generative AI capabilities to summarize incidents, suggest solutions, and generate content.',
    actions:['Summarize Incident','Generate Response','Suggest Solution','Summarize Chat','Generate Knowledge Article'],
    setup_steps:['Now Assist must be enabled in your ServiceNow tenant','Configure AI provider (ServiceNow AI, Azure OpenAI)'],
    common_errors:['Feature not enabled — requires Now Assist license'],
    min_version:'Vancouver', tags:['ai','genai','now-assist','llm'] },

  { slug:'aws-translate', name:'AWS Translate', icon:'🌐', category:'AI', tier:'starter',
    plugin_id:'com.snc.aws_translate_spoke', credential_type:'AWS Access Key',
    description:'Translate text between languages using AWS Translate from ServiceNow workflows. Supports auto-language detection.',
    actions:['Translate Text','Detect Language'],
    setup_steps:['Configure AWS credentials with TranslateFullAccess policy','Create Connection Alias with AWS key credentials'],
    common_errors:['UnsupportedLanguagePairException — check supported language codes'],
    min_version:'Utah', tags:['translation','aws','ai'] },

  { slug:'servicenow-notifications', name:'ServiceNow Notifications', icon:'🔔', category:'Communication', tier:'starter',
    plugin_id:'com.glide.notification', credential_type:'Internal',
    description:'Send email and push notifications from ServiceNow flows using the built-in notification engine.',
    actions:['Send Notification','Send Email','Look Up Notification'],
    setup_steps:['Configure email server in System Mailboxes','Set up notification devices for push'],
    common_errors:['Email not sent — check outbound email server configuration'],
    min_version:'New York', tags:['notifications','email'] },

  { slug:'servicenow-flow-designer', name:'Flow Designer Utilities', icon:'⚡', category:'Automation', tier:'starter',
    plugin_id:'com.glide.hub.action.base', credential_type:'Internal',
    description:'Core Flow Designer utility actions for data transformation, error handling, and flow control.',
    actions:['Set Values','Look Up Records','Create Record','Update Record','Delete Record','Ask for Approval','Wait for Condition','Transform XML','Parse JSON'],
    setup_steps:['Flow Designer is available on all instances','No additional configuration required'],
    common_errors:['Record not found — check table name and sys_id','Approval timed out — configure approval escalation'],
    min_version:'New York', tags:['flow-designer','automation','core'] },
];

module.exports = SPOKES;
